### PR TITLE
Implement IonHash support for list/sexp

### PR DESCRIPTION
**Pull request by marcbowes**
*Issue #, if available:*

*Description of changes:*

Implement IonHash support for list/sexp

Easy one! Minimal refactoring required to expose the `s(value)`
function. With that refactoring, some code de-duplication in the struct
repr was possible too.

All the list/sexps tests passed first time, for a change :).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by marcbowes** [comment]
Note this also contains the commit in #270 and should be reviewed in sequence (hah!).

**Review by almann — COMMENTED** [review]
Looks good, I only reviewed [76a2390][1], so I will wait until the dust settles on the pre-requisite before approving this one.

[1]: https://github.com/amzn/ion-rust/pull/271/commits/76a2390c02f9a337e4e4e2a84a9fb6b820c52e33

**Comment by marcbowes** [comment]
Rebased off #270 which is now merged.

**Review by almann — APPROVED** [review]
:shipit:

**Pull request merged**
