### PR TITLE
Add a ToIonDataSource implementation for std::io::Cursor and references to byte arrays.

### PR DESCRIPTION
**Pull request by jnicholls**
## What's changing?

* Adding an implementation of `ToIonDataSource` for `std::io::Cursor` for completeness.
* Adding an implementation of `ToIonDataSource` for `&[u8; N]` as an additional acceptable type for any method accepting a `ToIonDataSource`, such as the readers.
* Update the `IonDataSource` trait to have default implementations, since it requires BufRead.
* Update the `ToIonDataSource` to put a trait bound on the `DataSource` associated type of `IonDataSource` instead of `BufRead` which is more specific and correct.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by zslayton** [comment]
The change looks good, but the build is currently failing. Could you take a look when you have a chance?

**Comment by jnicholls** [comment]
Yeah, I forgot to add some files and test updates, sorry. I have a few branches going. I'll get back to this in a little bit. Thanks.

**Comment by jnicholls** [comment]
Seems like the builds are stuck pending... 🤷‍♂️

**Review by zslayton — APPROVED** [review]

**Comment by zslayton** [comment]
Thanks for the PR!

**Pull request merged**
