### PR TITLE
Delete NOTICE

### PR DESCRIPTION
**Pull request by Infinite-Blue-1042**
*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by almann** [comment]
Is there a reason why we'd delete the file rather than update the date in it?

**Comment by Infinite-Blue-1042** [comment]
Oh yeah, sorry about that. We could as well update the FIle's Date. Thanks for the Notice.

**Comment by Infinite-Blue-1042** [comment]
Do you know how I can become a contributor?

**Comment by almann** [comment]
> Do you know how I can become a contributor?

Feel free to take a look at our issues and choose something that looks small, we are always welcoming of PRs to the repository.  If you want to submit a cosmetic change like updating the `NOTICE`, feel free to re-open or submit a new PR with that change.

**Pull request closed without merging**
